### ISSUE TITLE
make fail.

### ISSUE THREAD

**Issue by dranandrao** [pmem/issues#941]
I cloned the repo and trying to execute make command but failing.
This is the error that it's throwing.

**src/common.inc:370: *** libndctl(version >= 60.1) is missing -- see README.  Stop.**

Please help me to get through.

**Comment by pbalcer** [comment]
See the dependencies section of PMDK's readme: https://github.com/pmem/pmdk#dependencies

For information on how to install ndctl, refer to ndctl's own page https://github.com/pmem/ndctl
You can install it from source, or you can install it directly from your distro package manager if it's present.

**Comment by dranandrao** [comment]
I have installed ndctl and its working fine.But Im facing that problem

**Comment by pbalcer** [comment]
I can see that you've installed the ndctl utility, but have you also installed the development files?
PMDK uses `pkg-config libndctl --atleast-version 60.1` command to verify if the library in the correct version is installed. If this command fails (after running it, check what's the output of `echo $?` - should be `0`), it means that ndctl was not correctly installed.

**Comment by marcinslusarz** [comment]
I think the problem is that we didn't document clearly enough what is needed to build. ndctl is not enough, and pmdk actually needs libndctl-**dev(el)**. I updated README to reflect that.

**Comment by zubair-apece** [comment]
Hi, I am facing same issue. Although I have installed ndctl as per the instruction. I can't install libndctl-dev(el). I am using ubuntu 16.4 and it fails to find this package. can anyone help?

**Comment by sscargal** [comment]
> I can't install libndctl-dev(el). I am using ubuntu 16.4 and it fails to find this package. can anyone help?

ndctl packages for Ubuntu are available in 18.04 and 18.10 or later.  See [https://packages.ubuntu.com/search?keywords=ndctl](https://packages.ubuntu.com/search?keywords=ndctl)

For 16.04, you'll need to compile ndctl from source.  See [https://docs.pmem.io/getting-started-guide/installing-ndctl](https://docs.pmem.io/getting-started-guide/installing-ndctl) and follow the 'Ubuntu' track (tabs).

Then you can switch to [Installing PMDK from source](https://docs.pmem.io/getting-started-guide/installing-pmdk/compiling-pmdk-from-source).  If you encounter the same `src/common.inc:370: *** libndctl(version >= 60.1) is missing -- see README.  Stop.` message again, there's a solution listed under the '**[Compile](https://docs.pmem.io/getting-started-guide/installing-pmdk/compiling-pmdk-from-source#compile)**' sub-heading to update your PKG_CONFIG_PATH to include the non-default search path for the *.pc files.

**Comment by zubair-apece** [comment]
Hi, I have compiled and installed ndctl from source in my ubuntu 16.04. It still shows *** libndctl is missing.
